// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ncp.Admin.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ncp.Admin.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ncp.Admin.Domain.AggregatesModel.DashboardAggregate.UserCalendarMemo", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasComment("便签标识");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasComment("便签内容");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<DateOnly>("MemoDate")
                        .HasColumnType("date")
                        .HasComment("便签日期");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("更新时间");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasComment("用户标识");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "MemoDate")
                        .IsUnique();

                    b.ToTable("user_calendar_memo", (string)null);
                });

            modelBuilder.Entity("Ncp.Admin.Domain.AggregatesModel.DashboardAggregate.UserHomeDashboardPreference", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasComment("用户标识");

                    b.Property<string>("CardOrderJson")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasComment("首页卡片排序 JSON");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("更新时间");

                    b.HasKey("Id");

                    b.ToTable("user_home_dashboard_preference", (string)null);
                });

            modelBuilder.Entity("Ncp.Admin.Domain.AggregatesModel.DeptAggregate.Dept", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasComment("部门标识");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<DateTimeOffset>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("删除时间");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("是否软删");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("部门名称");

                    b.Property<long>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("备注");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasComment("排序号");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasComment("状态（0=禁用，1=启用）");

                    b.Property<DateTimeOffset>("UpdateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("更新时间");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("ParentId");

                    b.HasIndex("SortOrder");

                    b.HasIndex("Status");

                    b.ToTable("dept", (string)null);
                });

            modelBuilder.Entity("Ncp.Admin.Domain.AggregatesModel.DeptAggregate.DeptResponsibleUser", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasComment("部门负责人关系标识");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<long>("DeptId")
                        .HasColumnType("bigint")
                        .HasComment("部门ID");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasComment("是否默认负责人");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasComment("排序号");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasComment("负责人用户ID");

                    b.HasKey("Id");

                    b.HasIndex("DeptId");

                    b.HasIndex("UserId");

                    b.HasIndex("DeptId", "UserId")
                        .IsUnique();

                    b.ToTable("dept_responsible_user", (string)null);
                });

            modelBuilder.Entity("Ncp.Admin.Domain.AggregatesModel.NotificationAggregate.Notification", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasComment("通知标识");

                    b.Property<string>("BusinessId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("业务ID（字符串）");

                    b.Property<string>("BusinessType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("业务类型");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasComment("内容");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<DateTimeOffset>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("删除时间");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("是否软删");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasComment("是否已读");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasComment("等级");

                    b.Property<DateTime>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("已读时间");

                    b.Property<long>("ReceiverId")
                        .HasColumnType("bigint")
                        .HasComment("接收人用户ID");

                    b.Property<long>("SenderId")
                        .HasColumnType("bigint")
                        .HasComment("发送人用户ID");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("发送人姓名");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("标题");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasComment("类型");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("IsRead");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("Type");

                    b.HasIndex("ReceiverId", "IsRead", "IsDeleted");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("Ncp.Admin.Domain.AggregatesModel.OperationLogAggregate.OperationLog", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasComment("操作日志ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("操作时间");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint")
                        .HasComment("请求耗时(毫秒)");

                    b.Property<int>("HttpStatusCode")
                        .HasColumnType("integer")
                        .HasComment("HTTP状态码");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("客户端IP");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean")
                        .HasComment("是否成功");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("模块名称");

                    b.Property<int>("OperationType")
                        .HasColumnType("integer")
                        .HasComment("操作类型");

                    b.Property<long>("OperatorUserId")
                        .HasColumnType("bigint")
                        .HasComment("操作人用户ID");

                    b.Property<string>("OperatorUserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("操作人姓名");

                    b.Property<string>("RequestBody")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasComment("请求入参(JSON,脱敏/截断)");

                    b.Property<string>("RequestMethod")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasComment("HTTP方法");

                    b.Property<string>("RequestPath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasComment("请求路径");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasComment("响应出参(JSON,脱敏/截断)");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasComment("User-Agent");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Module");

                    b.HasIndex("OperationType");

                    b.HasIndex("OperatorUserId");

                    b.ToTable("operation_log", (string)null);
                });

            modelBuilder.Entity("Ncp.Admin.Domain.AggregatesModel.PositionAggregate.Position", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasComment("岗位标识");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("岗位编码");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<DateTimeOffset>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("删除时间");

                    b.Property<long>("DeptId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("岗位描述");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("是否软删");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("岗位名称");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasComment("排序号");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasComment("状态（0=禁用，1=启用）");

                    b.Property<DateTimeOffset>("UpdateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("更新时间");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DeptId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Status");

                    b.ToTable("position", (string)null);
                });

            modelBuilder.Entity("Ncp.Admin.Domain.AggregatesModel.RoleAggregate.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasComment("角色标识");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<int>("DataScope")
                        .HasColumnType("integer")
                        .HasComment("数据权限范围");

                    b.Property<DateTimeOffset>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("角色描述");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasComment("是否启用");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("是否软删");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("角色名称");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("Ncp.Admin.Domain.AggregatesModel.RoleAggregate.RoleDataDept", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasComment("角色ID");

                    b.Property<long>("DeptId")
                        .HasColumnType("bigint")
                        .HasComment("部门ID");

                    b.HasKey("RoleId", "DeptId");

                    b.ToTable("role_data_dept", (string)null);
                });

            modelBuilder.Entity("Ncp.Admin.Domain.AggregatesModel.RoleAggregate.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasComment("角色ID");

                    b.Property<string>("PermissionCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("权限编码");

                    b.Property<string>("PermissionDescription")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("权限描述");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("权限名称");

                    b.HasKey("RoleId", "PermissionCode");

                    b.ToTable("role_permission", (string)null);
                });

            modelBuilder.Entity("Ncp.Admin.Domain.AggregatesModel.UserAggregate.User", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasComment("用户标识");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("地址");

                    b.Property<bool>("AttendanceRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasComment("是否需要参与考勤计算");

                    b.Property<int>("AttendanceRuleCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("考勤规则业务编码");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("头像地址");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("出生日期");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<long>("CreatorId")
                        .HasColumnType("bigint")
                        .HasComment("创建人用户ID");

                    b.Property<DateTimeOffset>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("删除时间");

                    b.Property<long>("DeleterId")
                        .HasColumnType("bigint")
                        .HasComment("删除人用户ID");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("学历");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("邮箱");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasComment("性别");

                    b.Property<string>("GraduateSchool")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("毕业院校");

                    b.Property<string>("IdCardNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("身份证号");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasComment("是否启用");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("是否已删除");

                    b.Property<bool>("IsResigned")
                        .HasColumnType("boolean")
                        .HasComment("是否离职");

                    b.Property<string>("LastLoginIp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("最后登录IP");

                    b.Property<DateTime>("LastLoginTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("最后登录时间");

                    b.Property<long>("ModifierId")
                        .HasColumnType("bigint")
                        .HasComment("修改人用户ID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("用户名");

                    b.Property<bool>("NotOrderMeal")
                        .HasColumnType("boolean")
                        .HasComment("是否不订餐");

                    b.Property<int>("OrderMealSort")
                        .HasColumnType("integer")
                        .HasComment("订餐排序");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("密码哈希");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("手机号");

                    b.Property<string>("RealName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("真实姓名");

                    b.Property<DateTime>("ResignedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("离职时间");

                    b.Property<int>("RowVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("更新时间");

                    b.Property<string>("WechatGuid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasComment("唯一码");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("Name");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Ncp.Admin.Domain.AggregatesModel.UserAggregate.UserDept", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("UserId");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("DeptId")
                        .HasColumnType("bigint");

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("DeptId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("user_dept", (string)null);
                });

            modelBuilder.Entity("Ncp.Admin.Domain.AggregatesModel.UserAggregate.UserPosition", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("UserId");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("PositionId")
                        .HasColumnType("bigint");

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("PositionId");

                    b.ToTable("user_position", (string)null);
                });

            modelBuilder.Entity("Ncp.Admin.Domain.AggregatesModel.UserAggregate.UserRefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_refresh_token", (string)null);
                });

            modelBuilder.Entity("Ncp.Admin.Domain.AggregatesModel.UserAggregate.UserRole", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("user_role", (string)null);
                });

            modelBuilder.Entity("Ncp.Admin.Domain.AggregatesModel.WorkflowDefinitionAggregate.WorkflowDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasComment("主键");

                    b.Property<Guid>("BasedOnId")
                        .HasColumnType("uuid")
                        .HasComment("基于哪条流程定义创建（新版本时指向源定义，发布时据此归档源）");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("流程分类");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<long>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasComment("创建人ID");

                    b.Property<DateTimeOffset>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("删除时间");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("流程描述");

                    b.Property<string>("DesignerSchemaJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("设计器 Schema JSON");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasComment("是否删除");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("流程名称");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasComment("流程状态：0草稿 1已发布 2已归档");

                    b.Property<DateTimeOffset>("UpdateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("更新时间");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasComment("版本号");

                    b.HasKey("Id");

                    b.HasIndex("BasedOnId");

                    b.HasIndex("Category");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name");

                    b.HasIndex("Status");

                    b.ToTable("workflow_definition", (string)null);
                });

            modelBuilder.Entity("Ncp.Admin.Domain.AggregatesModel.WorkflowDefinitionAggregate.WorkflowDefinitionVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasComment("主键");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<string>("DesignerSchemaJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("前端设计器 JSON");

                    b.Property<string>("GraphSnapshotJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("发布后的运行图快照 JSON");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("发布时间");

                    b.Property<long>("PublishedBy")
                        .HasColumnType("bigint")
                        .HasComment("发布人ID");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasComment("版本状态：0草稿 1已发布 2已归档");

                    b.Property<DateTimeOffset>("UpdateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("更新时间");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasComment("版本号");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("uuid")
                        .HasComment("流程定义ID");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowDefinitionId");

                    b.HasIndex("WorkflowDefinitionId", "Status");

                    b.HasIndex("WorkflowDefinitionId", "Version")
                        .IsUnique();

                    b.ToTable("workflow_definition_version", (string)null);
                });

            modelBuilder.Entity("Ncp.Admin.Domain.AggregatesModel.WorkflowInstanceAggregate.WorkflowInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasComment("主键");

                    b.Property<string>("BusinessKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("业务关联键");

                    b.Property<string>("BusinessType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("业务类型");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("完成时间");

                    b.Property<string>("CurrentNodeKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("当前节点key");

                    b.Property<string>("CurrentNodeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("当前节点名称");

                    b.Property<string>("FailureReason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasComment("业务执行失败原因");

                    b.Property<long>("InitiatorDeptId")
                        .HasColumnType("bigint")
                        .HasComment("发起人部门ID");

                    b.Property<long>("InitiatorId")
                        .HasColumnType("bigint")
                        .HasComment("发起人ID");

                    b.Property<string>("InitiatorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("发起人姓名");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasComment("备注");

                    b.Property<DateTime>("ResumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("最近一次恢复时间");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("开始时间");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasComment("流程状态");

                    b.Property<DateTime>("SuspendedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("最近一次挂起时间");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("流程标题");

                    b.Property<string>("Variables")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("流程变量JSON");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("uuid")
                        .HasComment("流程定义ID");

                    b.Property<string>("WorkflowDefinitionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("流程定义名称");

                    b.Property<Guid>("WorkflowDefinitionVersionId")
                        .HasColumnType("uuid")
                        .HasComment("流程定义版本ID");

                    b.HasKey("Id");

                    b.HasIndex("BusinessKey");

                    b.HasIndex("BusinessType");

                    b.HasIndex("InitiatorDeptId");

                    b.HasIndex("InitiatorId");

                    b.HasIndex("Status");

                    b.HasIndex("WorkflowDefinitionId");

                    b.HasIndex("WorkflowDefinitionVersionId");

                    b.HasIndex("BusinessType", "BusinessKey")
                        .IsUnique()
                        .HasDatabaseName("ix_workflow_instance_active_business")
                        .HasFilter("\"Status\" IN (0, 1)");

                    b.HasIndex("BusinessType", "BusinessKey", "Status");

                    b.ToTable("workflow_instance", (string)null);
                });

            modelBuilder.Entity("Ncp.Admin.Domain.AggregatesModel.WorkflowInstanceAggregate.WorkflowTask", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasComment("主键");

                    b.Property<long>("AssigneeId")
                        .HasColumnType("bigint")
                        .HasComment("处理人用户ID（按角色任务时为 0）");

                    b.Property<string>("AssigneeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("处理人姓名/角色名");

                    b.Property<Guid>("AssigneeRoleId")
                        .HasColumnType("uuid")
                        .HasComment("处理人角色ID（按用户任务时为 Guid.Empty）");

                    b.Property<int>("AssigneeType")
                        .HasColumnType("integer")
                        .HasComment("处理人类型：0用户 1角色");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasComment("审批意见");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("完成时间");

                    b.Property<long>("CompletedByUserId")
                        .HasColumnType("bigint")
                        .HasComment("审批通过时的实际操作人用户ID（角色任务等用于追溯）");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<string>("ExtraDataJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("任务扩展数据JSON");

                    b.Property<string>("NodeKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("节点key");

                    b.Property<string>("NodeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("节点名称");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasComment("任务状态");

                    b.Property<int>("TaskType")
                        .HasColumnType("integer")
                        .HasComment("任务类型：0审批 1通知 2抄送");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkflowInstanceId")
                        .HasColumnType("uuid")
                        .HasComment("流程实例ID");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("AssigneeRoleId");

                    b.HasIndex("Status");

                    b.HasIndex("WorkflowInstanceId");

                    b.HasIndex("AssigneeId", "Status");

                    b.ToTable("workflow_task", (string)null);
                });

            modelBuilder.Entity("Ncp.Admin.Domain.AggregatesModel.WorkflowInstanceAggregate.WorkflowTaskAssignmentSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasComment("主键");

                    b.Property<string>("AssigneeDisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("处理人显示名");

                    b.Property<Guid>("AssigneeRoleId")
                        .HasColumnType("uuid")
                        .HasComment("处理人角色ID");

                    b.Property<int>("AssigneeType")
                        .HasColumnType("integer")
                        .HasComment("处理人类型：0用户 1角色");

                    b.Property<long>("AssigneeUserId")
                        .HasColumnType("bigint")
                        .HasComment("处理人用户ID");

                    b.Property<int>("AssignmentSource")
                        .HasColumnType("integer")
                        .HasComment("授权来源");

                    b.Property<bool>("BypassDataPermission")
                        .HasColumnType("boolean")
                        .HasComment("是否绕过常规数据权限过滤");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("创建时间");

                    b.Property<string>("CreatedReason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("创建原因");

                    b.Property<string>("InitiatorDeptScopeDeptIdsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("配置的发起部门范围JSON");

                    b.Property<int>("InitiatorDeptScopeMode")
                        .HasColumnType("integer")
                        .HasComment("发起部门范围模式");

                    b.Property<string>("SourceRuleId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("来源规则ID");

                    b.Property<int>("VisibilityMode")
                        .HasColumnType("integer")
                        .HasComment("可见性模式");

                    b.Property<Guid>("WorkflowTaskId")
                        .HasColumnType("uuid")
                        .HasComment("任务ID");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeRoleId");

                    b.HasIndex("AssigneeUserId");

                    b.HasIndex("WorkflowTaskId");

                    b.HasIndex("AssigneeRoleId", "WorkflowTaskId");

                    b.HasIndex("AssigneeUserId", "WorkflowTaskId");

                    b.ToTable("workflow_task_assignment_snapshot", (string)null);
                });

            modelBuilder.Entity("NetCorePal.Extensions.DistributedTransactions.CAP.Persistence.CapLock", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Instance")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("LastLockTime")
                        .HasColumnType("TIMESTAMP");

                    b.HasKey("Key");

                    b.ToTable("CAPLock", (string)null);
                });

            modelBuilder.Entity("NetCorePal.Extensions.DistributedTransactions.CAP.Persistence.PublishedMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Added")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("Retries")
                        .HasColumnType("integer");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Version")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ExpiresAt", "StatusName" }, "IX_ExpiresAt_StatusName");

                    b.HasIndex(new[] { "Version", "ExpiresAt", "StatusName" }, "IX_Version_ExpiresAt_StatusName");

                    b.ToTable("CAPPublishedMessage", (string)null);
                });

            modelBuilder.Entity("NetCorePal.Extensions.DistributedTransactions.CAP.Persistence.ReceivedMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Added")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TIMESTAMP");

                    b.Property<string>("Group")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<int?>("Retries")
                        .HasColumnType("integer");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Version")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ExpiresAt", "StatusName" }, "IX_ExpiresAt_StatusName")
                        .HasDatabaseName("IX_ExpiresAt_StatusName1");

                    b.HasIndex(new[] { "Version", "ExpiresAt", "StatusName" }, "IX_Version_ExpiresAt_StatusName")
                        .HasDatabaseName("IX_Version_ExpiresAt_StatusName1");

                    b.ToTable("CAPReceivedMessage", (string)null);
                });

            modelBuilder.Entity("Ncp.Admin.Domain.AggregatesModel.DeptAggregate.DeptResponsibleUser", b =>
                {
                    b.HasOne("Ncp.Admin.Domain.AggregatesModel.DeptAggregate.Dept", null)
                        .WithMany("ResponsibleUsers")
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ncp.Admin.Domain.AggregatesModel.RoleAggregate.RoleDataDept", b =>
                {
                    b.HasOne("Ncp.Admin.Domain.AggregatesModel.RoleAggregate.Role", null)
                        .WithMany("DataDepts")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ncp.Admin.Domain.AggregatesModel.RoleAggregate.RolePermission", b =>
                {
                    b.HasOne("Ncp.Admin.Domain.AggregatesModel.RoleAggregate.Role", null)
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ncp.Admin.Domain.AggregatesModel.UserAggregate.UserDept", b =>
                {
                    b.HasOne("Ncp.Admin.Domain.AggregatesModel.UserAggregate.User", null)
                        .WithOne("Dept")
                        .HasForeignKey("Ncp.Admin.Domain.AggregatesModel.UserAggregate.UserDept", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ncp.Admin.Domain.AggregatesModel.UserAggregate.UserPosition", b =>
                {
                    b.HasOne("Ncp.Admin.Domain.AggregatesModel.UserAggregate.User", null)
                        .WithOne("Position")
                        .HasForeignKey("Ncp.Admin.Domain.AggregatesModel.UserAggregate.UserPosition", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ncp.Admin.Domain.AggregatesModel.UserAggregate.UserRefreshToken", b =>
                {
                    b.HasOne("Ncp.Admin.Domain.AggregatesModel.UserAggregate.User", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ncp.Admin.Domain.AggregatesModel.UserAggregate.UserRole", b =>
                {
                    b.HasOne("Ncp.Admin.Domain.AggregatesModel.UserAggregate.User", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ncp.Admin.Domain.AggregatesModel.WorkflowDefinitionAggregate.WorkflowDefinitionVersion", b =>
                {
                    b.HasOne("Ncp.Admin.Domain.AggregatesModel.WorkflowDefinitionAggregate.WorkflowDefinition", null)
                        .WithMany("Versions")
                        .HasForeignKey("WorkflowDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ncp.Admin.Domain.AggregatesModel.WorkflowInstanceAggregate.WorkflowTask", b =>
                {
                    b.HasOne("Ncp.Admin.Domain.AggregatesModel.WorkflowInstanceAggregate.WorkflowInstance", null)
                        .WithMany("Tasks")
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ncp.Admin.Domain.AggregatesModel.WorkflowInstanceAggregate.WorkflowTaskAssignmentSnapshot", b =>
                {
                    b.HasOne("Ncp.Admin.Domain.AggregatesModel.WorkflowInstanceAggregate.WorkflowTask", null)
                        .WithMany("AssignmentSnapshots")
                        .HasForeignKey("WorkflowTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ncp.Admin.Domain.AggregatesModel.DeptAggregate.Dept", b =>
                {
                    b.Navigation("ResponsibleUsers");
                });

            modelBuilder.Entity("Ncp.Admin.Domain.AggregatesModel.RoleAggregate.Role", b =>
                {
                    b.Navigation("DataDepts");

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Ncp.Admin.Domain.AggregatesModel.UserAggregate.User", b =>
                {
                    b.Navigation("Dept")
                        .IsRequired();

                    b.Navigation("Position")
                        .IsRequired();

                    b.Navigation("RefreshTokens");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Ncp.Admin.Domain.AggregatesModel.WorkflowDefinitionAggregate.WorkflowDefinition", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Ncp.Admin.Domain.AggregatesModel.WorkflowInstanceAggregate.WorkflowInstance", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Ncp.Admin.Domain.AggregatesModel.WorkflowInstanceAggregate.WorkflowTask", b =>
                {
                    b.Navigation("AssignmentSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
